// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// AggregateStage structs contains the metrics for the aggregate_stage group.
type AggregateStage struct {
	aggregateMessages atomic.Int64
}

// NewAggregateStage returns a new instance of the AggregateStage struct.
func NewAggregateStage() *AggregateStage {
	return &AggregateStage{}
}

// InitMetrics initializes the metrics for the AggregateStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *AggregateStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize aggregate_messages metric
	err = tel.NewCounterMetric(
		"aggregate_messages",
		func() int64 { return m.aggregateMessages.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddAggregateMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *AggregateStage) AddAggregateMessages(amount int) {
	m.aggregateMessages.Add(int64(amount))
}

// IncrementAggregateMessages increments the metric by 1.
func (m *AggregateStage) IncrementAggregateMessages() {
	m.aggregateMessages.Add(1)
}

// DecrementAggregateMessages decrements the metric by 1.
func (m *AggregateStage) DecrementAggregateMessages() {
	m.aggregateMessages.Add(-1)
}
