// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// CanStage structs contains the metrics for the can_stage group.
type CanStage struct {
	canMessages atomic.Int64
	canSignals  atomic.Int64
}

// NewCanStage returns a new instance of the CanStage struct.
func NewCanStage() *CanStage {
	return &CanStage{}
}

// InitMetrics initializes the metrics for the CanStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *CanStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize can_messages counter metric
	err = tel.NewCounterMetric("can_messages", func() int64 { return m.canMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize can_signals counter metric
	err = tel.NewCounterMetric("can_signals", func() int64 { return m.canSignals.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddCanMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *CanStage) AddCanMessages(amount uint) {
	m.canMessages.Add(int64(amount))
}

// IncrementCanMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *CanStage) IncrementCanMessages() {
	m.canMessages.Add(1)
}

// AddCanSignals adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *CanStage) AddCanSignals(amount uint) {
	m.canSignals.Add(int64(amount))
}

// IncrementCanSignals increments the counter metric by 1.
//
// This function is thread-safe.
func (m *CanStage) IncrementCanSignals() {
	m.canSignals.Add(1)
}
