// Code generated by metrics-gen. DO NOT EDIT.

package metrics

type JsonDecoderErrorType string

const (
	JsonDecoderErrorTypeInputTooLarge JsonDecoderErrorType = "goccia.json.input_too_large"
	JsonDecoderErrorTypeNullRejected  JsonDecoderErrorType = "goccia.json.null_rejected"
	JsonDecoderErrorTypeTrailingValue JsonDecoderErrorType = "goccia.json.trailing_value"
	JsonDecoderErrorTypeSyntaxError   JsonDecoderErrorType = "goccia.json.syntax_error"
	JsonDecoderErrorTypeTypeError     JsonDecoderErrorType = "goccia.json.type_error"
	JsonDecoderErrorTypeUnknownField  JsonDecoderErrorType = "goccia.json.unknown_field"
	JsonDecoderErrorTypeOther         JsonDecoderErrorType = "_OTHER"
)

type JsonEncoderErrorType string

const (
	JsonEncoderErrorTypeUnsupportedType  JsonEncoderErrorType = "goccia.json.unsupported_type"
	JsonEncoderErrorTypeUnsupportedValue JsonEncoderErrorType = "goccia.json.unsupported_value"
	JsonEncoderErrorTypeMarshalerError   JsonEncoderErrorType = "goccia.json.marshaler_error"
	JsonEncoderErrorTypeOther            JsonEncoderErrorType = "_OTHER"
)
