// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// FilterStage structs contains the metrics for the filter_stage group.
type FilterStage struct {
	filteredMessages atomic.Int64
}

// NewFilterStage returns a new instance of the FilterStage struct.
func NewFilterStage() *FilterStage {
	return &FilterStage{}
}

// InitMetrics initializes the metrics for the FilterStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *FilterStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize filtered_messages counter metric
	err = tel.NewCounterMetric("filtered_messages", func() int64 { return m.filteredMessages.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddFilteredMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *FilterStage) AddFilteredMessages(amount uint) {
	m.filteredMessages.Add(int64(amount))
}

// IncrementFilteredMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *FilterStage) IncrementFilteredMessages() {
	m.filteredMessages.Add(1)
}
