// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// JsonDecoder structs contains the metrics for the json_decoder group.
type JsonDecoder struct {
	gocciaJsonDecoderOperationDuration *telemetry.FloatHistogram
	gocciaJsonDecoderInputSize         *telemetry.IntHistogram
}

// NewJsonDecoder returns a new instance of the JsonDecoder struct.
func NewJsonDecoder() *JsonDecoder {
	return &JsonDecoder{}
}

// InitMetrics initializes the metrics for the JsonDecoder.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *JsonDecoder) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize goccia.json.decoder.operation.duration metric
	m.gocciaJsonDecoderOperationDuration, err = tel.NewFloatHistogramMetric(
		"goccia.json.decoder.operation.duration",
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(
			1e-06, 2.5e-06, 5e-06, 1e-05, 2.5e-05, 5e-05, 0.0001, 0.00025, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10,
		),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.json.decoder.input.size metric
	m.gocciaJsonDecoderInputSize, err = tel.NewIntHistogramMetric(
		"goccia.json.decoder.input.size",
		metric.WithUnit("By"),
	)
	if err != nil {
		return err
	}

	return nil
}

// RecordGocciaJsonDecoderOperationDuration records the given value into the histogram metric.
func (m *JsonDecoder) RecordGocciaJsonDecoderOperationDuration(
	ctx context.Context,
	value float64,
	errType string,
) {
	m.gocciaJsonDecoderOperationDuration.Record(
		ctx,
		value,
		attribute.String("error.type", errType),
	)
}

// RecordGocciaJsonDecoderOperationDurationWithAttributes records the given value
// ans attributes into the histogram metric.
func (m *JsonDecoder) RecordGocciaJsonDecoderOperationDurationWithAttributes(
	ctx context.Context,
	value float64,
	attributes metric.MeasurementOption,
) {
	m.gocciaJsonDecoderOperationDuration.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}

// RecordGocciaJsonDecoderInputSize records the given value into the histogram metric.
func (m *JsonDecoder) RecordGocciaJsonDecoderInputSize(
	ctx context.Context,
	value int64,
	errType string,
) {
	m.gocciaJsonDecoderInputSize.Record(
		ctx,
		value,
		attribute.String("error.type", errType),
	)
}

// RecordGocciaJsonDecoderInputSizeWithAttributes records the given value
// ans attributes into the histogram metric.
func (m *JsonDecoder) RecordGocciaJsonDecoderInputSizeWithAttributes(
	ctx context.Context,
	value int64,
	attributes metric.MeasurementOption,
) {
	m.gocciaJsonDecoderInputSize.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}
