// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// JsonEncoder structs contains the metrics for the json_encoder group.
type JsonEncoder struct {
	gocciaJsonEncoderOperationDuration *telemetry.FloatHistogram
	gocciaJsonEncoderOutputSize        *telemetry.IntHistogram
	jsonEncoderErrorTypes              map[JsonEncoderErrorType]metric.MeasurementOption
}

// NewJsonEncoder returns a new instance of the JsonEncoder struct.
func NewJsonEncoder() *JsonEncoder {
	return &JsonEncoder{}
}

// InitMetrics initializes the metrics for the JsonEncoder.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *JsonEncoder) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize goccia.json.encoder.operation.duration metric
	m.gocciaJsonEncoderOperationDuration, err = tel.NewFloatHistogramMetric(
		"goccia.json.encoder.operation.duration",
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(
			1e-06, 2.5e-06, 5e-06, 1e-05, 2.5e-05, 5e-05, 0.0001, 0.00025, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10,
		),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.json.encoder.output.size metric
	m.gocciaJsonEncoderOutputSize, err = tel.NewIntHistogramMetric(
		"goccia.json.encoder.output.size",
		metric.WithUnit("By"),
	)
	if err != nil {
		return err
	}

	m.jsonEncoderErrorTypes = map[JsonEncoderErrorType]metric.MeasurementOption{
		JsonEncoderErrorTypeUnsupportedType: metric.WithAttributes(
			attribute.String("error.type", string(JsonEncoderErrorTypeUnsupportedType)),
		),
		JsonEncoderErrorTypeUnsupportedValue: metric.WithAttributes(
			attribute.String("error.type", string(JsonEncoderErrorTypeUnsupportedValue)),
		),
		JsonEncoderErrorTypeMarshalerError: metric.WithAttributes(
			attribute.String("error.type", string(JsonEncoderErrorTypeMarshalerError)),
		),
		JsonEncoderErrorTypeOther: metric.WithAttributes(
			attribute.String("error.type", "_OTHER"),
		),
	}
	return nil
}

// RecordGocciaJsonEncoderOperationDuration records the given value into the histogram metric.
func (m *JsonEncoder) RecordGocciaJsonEncoderOperationDuration(
	ctx context.Context,
	value float64,
) {
	m.gocciaJsonEncoderOperationDuration.Record(
		ctx,
		value,
	)
}

// RecordGocciaJsonEncoderOperationDurationWithAttributes records the given value
// and attributes into the histogram metric.
func (m *JsonEncoder) RecordGocciaJsonEncoderOperationDurationWithAttributes(
	ctx context.Context,
	value float64,
	attributes metric.MeasurementOption,
) {
	m.gocciaJsonEncoderOperationDuration.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}

// RecordGocciaJsonEncoderOperationDurationWithErrorType records the given value
// and the error type into the histogram metric.
func (m *JsonEncoder) RecordGocciaJsonEncoderOperationDurationWithErrorType(
	ctx context.Context,
	value float64,
	errorType JsonEncoderErrorType,
) {
	m.gocciaJsonEncoderOperationDuration.RecordWithAttributes(
		ctx,
		value,
		m.jsonEncoderErrorTypes[errorType],
	)
}

// RecordGocciaJsonEncoderOutputSize records the given value into the histogram metric.
func (m *JsonEncoder) RecordGocciaJsonEncoderOutputSize(
	ctx context.Context,
	value int64,
) {
	m.gocciaJsonEncoderOutputSize.Record(
		ctx,
		value,
	)
}

// RecordGocciaJsonEncoderOutputSizeWithAttributes records the given value
// and attributes into the histogram metric.
func (m *JsonEncoder) RecordGocciaJsonEncoderOutputSizeWithAttributes(
	ctx context.Context,
	value int64,
	attributes metric.MeasurementOption,
) {
	m.gocciaJsonEncoderOutputSize.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}
