// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// RobStage structs contains the metrics for the rob_stage group.
type RobStage struct {
	orderedMessages           atomic.Int64
	primaryEnqueuedMessages   atomic.Int64
	auxiliaryEnqueuedMessages atomic.Int64
	outOfOrderSequenceNumber  atomic.Int64
	duplicatedSequenceNumber  atomic.Int64
	invalidSequenceNumber     atomic.Int64
	resets                    atomic.Int64
}

// NewRobStage returns a new instance of the RobStage struct.
func NewRobStage() *RobStage {
	return &RobStage{}
}

// InitMetrics initializes the metrics for the RobStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *RobStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize ordered_messages metric
	err = tel.NewCounterMetric(
		"ordered_messages",
		func() int64 { return m.orderedMessages.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize primary_enqueued_messages metric
	err = tel.NewCounterMetric(
		"primary_enqueued_messages",
		func() int64 { return m.primaryEnqueuedMessages.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize auxiliary_enqueued_messages metric
	err = tel.NewCounterMetric(
		"auxiliary_enqueued_messages",
		func() int64 { return m.auxiliaryEnqueuedMessages.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize out_of_order_sequence_number metric
	err = tel.NewCounterMetric(
		"out_of_order_sequence_number",
		func() int64 { return m.outOfOrderSequenceNumber.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize duplicated_sequence_number metric
	err = tel.NewCounterMetric(
		"duplicated_sequence_number",
		func() int64 { return m.duplicatedSequenceNumber.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize invalid_sequence_number metric
	err = tel.NewCounterMetric(
		"invalid_sequence_number",
		func() int64 { return m.invalidSequenceNumber.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize resets metric
	err = tel.NewCounterMetric(
		"resets",
		func() int64 { return m.resets.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddOrderedMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddOrderedMessages(amount int) {
	m.orderedMessages.Add(int64(amount))
}

// IncrementOrderedMessages increments the metric by 1.
func (m *RobStage) IncrementOrderedMessages() {
	m.orderedMessages.Add(1)
}

// DecrementOrderedMessages decrements the metric by 1.
func (m *RobStage) DecrementOrderedMessages() {
	m.orderedMessages.Add(-1)
}

// AddPrimaryEnqueuedMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddPrimaryEnqueuedMessages(amount int) {
	m.primaryEnqueuedMessages.Add(int64(amount))
}

// IncrementPrimaryEnqueuedMessages increments the metric by 1.
func (m *RobStage) IncrementPrimaryEnqueuedMessages() {
	m.primaryEnqueuedMessages.Add(1)
}

// DecrementPrimaryEnqueuedMessages decrements the metric by 1.
func (m *RobStage) DecrementPrimaryEnqueuedMessages() {
	m.primaryEnqueuedMessages.Add(-1)
}

// AddAuxiliaryEnqueuedMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddAuxiliaryEnqueuedMessages(amount int) {
	m.auxiliaryEnqueuedMessages.Add(int64(amount))
}

// IncrementAuxiliaryEnqueuedMessages increments the metric by 1.
func (m *RobStage) IncrementAuxiliaryEnqueuedMessages() {
	m.auxiliaryEnqueuedMessages.Add(1)
}

// DecrementAuxiliaryEnqueuedMessages decrements the metric by 1.
func (m *RobStage) DecrementAuxiliaryEnqueuedMessages() {
	m.auxiliaryEnqueuedMessages.Add(-1)
}

// AddOutOfOrderSequenceNumber adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddOutOfOrderSequenceNumber(amount int) {
	m.outOfOrderSequenceNumber.Add(int64(amount))
}

// IncrementOutOfOrderSequenceNumber increments the metric by 1.
func (m *RobStage) IncrementOutOfOrderSequenceNumber() {
	m.outOfOrderSequenceNumber.Add(1)
}

// DecrementOutOfOrderSequenceNumber decrements the metric by 1.
func (m *RobStage) DecrementOutOfOrderSequenceNumber() {
	m.outOfOrderSequenceNumber.Add(-1)
}

// AddDuplicatedSequenceNumber adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddDuplicatedSequenceNumber(amount int) {
	m.duplicatedSequenceNumber.Add(int64(amount))
}

// IncrementDuplicatedSequenceNumber increments the metric by 1.
func (m *RobStage) IncrementDuplicatedSequenceNumber() {
	m.duplicatedSequenceNumber.Add(1)
}

// DecrementDuplicatedSequenceNumber decrements the metric by 1.
func (m *RobStage) DecrementDuplicatedSequenceNumber() {
	m.duplicatedSequenceNumber.Add(-1)
}

// AddInvalidSequenceNumber adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddInvalidSequenceNumber(amount int) {
	m.invalidSequenceNumber.Add(int64(amount))
}

// IncrementInvalidSequenceNumber increments the metric by 1.
func (m *RobStage) IncrementInvalidSequenceNumber() {
	m.invalidSequenceNumber.Add(1)
}

// DecrementInvalidSequenceNumber decrements the metric by 1.
func (m *RobStage) DecrementInvalidSequenceNumber() {
	m.invalidSequenceNumber.Add(-1)
}

// AddResets adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RobStage) AddResets(amount int) {
	m.resets.Add(int64(amount))
}

// IncrementResets increments the metric by 1.
func (m *RobStage) IncrementResets() {
	m.resets.Add(1)
}

// DecrementResets decrements the metric by 1.
func (m *RobStage) DecrementResets() {
	m.resets.Add(-1)
}
