// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// RobStage structs contains the metrics for the ROB_stage group.
type RobStage struct {
	orderedMessages           atomic.Int64
	primaryEnqueuedMessages   atomic.Int64
	auxiliaryEnqueuedMessages atomic.Int64
	outOfOrderSequenceNumber  atomic.Int64
	duplicatedSequenceNumber  atomic.Int64
	invalidSequenceNumber     atomic.Int64
	resets                    atomic.Int64
}

// NewRobStage returns a new instance of the RobStage struct.
func NewRobStage() *RobStage {
	return &RobStage{}
}

// InitMetrics initializes the metrics for the RobStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *RobStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize ordered_messages counter metric
	err = tel.NewCounterMetric("ordered_messages", func() int64 { return m.orderedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize primary_enqueued_messages counter metric
	err = tel.NewCounterMetric("primary_enqueued_messages", func() int64 { return m.primaryEnqueuedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize auxiliary_enqueued_messages counter metric
	err = tel.NewCounterMetric("auxiliary_enqueued_messages", func() int64 { return m.auxiliaryEnqueuedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize out_of_order_sequence_number counter metric
	err = tel.NewCounterMetric("out_of_order_sequence_number", func() int64 { return m.outOfOrderSequenceNumber.Load() })
	if err != nil {
		return err
	}

	// Initialize duplicated_sequence_number counter metric
	err = tel.NewCounterMetric("duplicated_sequence_number", func() int64 { return m.duplicatedSequenceNumber.Load() })
	if err != nil {
		return err
	}

	// Initialize invalid_sequence_number counter metric
	err = tel.NewCounterMetric("invalid_sequence_number", func() int64 { return m.invalidSequenceNumber.Load() })
	if err != nil {
		return err
	}

	// Initialize resets counter metric
	err = tel.NewCounterMetric("resets", func() int64 { return m.resets.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddOrderedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddOrderedMessages(amount uint) {
	m.orderedMessages.Add(int64(amount))
}

// IncrementOrderedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementOrderedMessages() {
	m.orderedMessages.Add(1)
}

// AddPrimaryEnqueuedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddPrimaryEnqueuedMessages(amount uint) {
	m.primaryEnqueuedMessages.Add(int64(amount))
}

// IncrementPrimaryEnqueuedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementPrimaryEnqueuedMessages() {
	m.primaryEnqueuedMessages.Add(1)
}

// AddAuxiliaryEnqueuedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddAuxiliaryEnqueuedMessages(amount uint) {
	m.auxiliaryEnqueuedMessages.Add(int64(amount))
}

// IncrementAuxiliaryEnqueuedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementAuxiliaryEnqueuedMessages() {
	m.auxiliaryEnqueuedMessages.Add(1)
}

// AddOutOfOrderSequenceNumber adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddOutOfOrderSequenceNumber(amount uint) {
	m.outOfOrderSequenceNumber.Add(int64(amount))
}

// IncrementOutOfOrderSequenceNumber increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementOutOfOrderSequenceNumber() {
	m.outOfOrderSequenceNumber.Add(1)
}

// AddDuplicatedSequenceNumber adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddDuplicatedSequenceNumber(amount uint) {
	m.duplicatedSequenceNumber.Add(int64(amount))
}

// IncrementDuplicatedSequenceNumber increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementDuplicatedSequenceNumber() {
	m.duplicatedSequenceNumber.Add(1)
}

// AddInvalidSequenceNumber adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddInvalidSequenceNumber(amount uint) {
	m.invalidSequenceNumber.Add(int64(amount))
}

// IncrementInvalidSequenceNumber increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementInvalidSequenceNumber() {
	m.invalidSequenceNumber.Add(1)
}

// AddResets adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RobStage) AddResets(amount uint) {
	m.resets.Add(int64(amount))
}

// IncrementResets increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RobStage) IncrementResets() {
	m.resets.Add(1)
}
