// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// RouterStage structs contains the metrics for the router_stage group.
type RouterStage struct {
	totalRoutedMessages atomic.Int64
}

// NewRouterStage returns a new instance of the RouterStage struct.
func NewRouterStage() *RouterStage {
	return &RouterStage{}
}

// InitMetrics initializes the metrics for the RouterStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *RouterStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize total_routed_messages metric
	err = tel.NewCounterMetric(
		"total_routed_messages",
		func() int64 { return m.totalRoutedMessages.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddTotalRoutedMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *RouterStage) AddTotalRoutedMessages(amount int) {
	m.totalRoutedMessages.Add(int64(amount))
}

// IncrementTotalRoutedMessages increments the metric by 1.
func (m *RouterStage) IncrementTotalRoutedMessages() {
	m.totalRoutedMessages.Add(1)
}

// DecrementTotalRoutedMessages decrements the metric by 1.
func (m *RouterStage) DecrementTotalRoutedMessages() {
	m.totalRoutedMessages.Add(-1)
}
