// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// RouterStage structs contains the metrics for the router_stage group.
type RouterStage struct {
	totalRoutedMessages atomic.Int64
}

// NewRouterStage returns a new instance of the RouterStage struct.
func NewRouterStage() *RouterStage {
	return &RouterStage{}
}

// InitMetrics initializes the metrics for the RouterStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *RouterStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize total_routed_messages counter metric
	err = tel.NewCounterMetric("total_routed_messages", func() int64 { return m.totalRoutedMessages.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddTotalRoutedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *RouterStage) AddTotalRoutedMessages(amount uint) {
	m.totalRoutedMessages.Add(int64(amount))
}

// IncrementTotalRoutedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *RouterStage) IncrementTotalRoutedMessages() {
	m.totalRoutedMessages.Add(1)
}
