// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// TeeStage structs contains the metrics for the tee_stage group.
type TeeStage struct {
	clonedMessages atomic.Int64
}

// NewTeeStage returns a new instance of the TeeStage struct.
func NewTeeStage() *TeeStage {
	return &TeeStage{}
}

// InitMetrics initializes the metrics for the TeeStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *TeeStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize cloned_messages counter metric
	err = tel.NewCounterMetric("cloned_messages", func() int64 { return m.clonedMessages.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddClonedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *TeeStage) AddClonedMessages(amount uint) {
	m.clonedMessages.Add(int64(amount))
}

// IncrementClonedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *TeeStage) IncrementClonedMessages() {
	m.clonedMessages.Add(1)
}
