// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// TeeStage structs contains the metrics for the tee_stage group.
type TeeStage struct {
	clonedMessages atomic.Int64
}

// NewTeeStage returns a new instance of the TeeStage struct.
func NewTeeStage() *TeeStage {
	return &TeeStage{}
}

// InitMetrics initializes the metrics for the TeeStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *TeeStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize cloned_messages metric
	err = tel.NewCounterMetric(
		"cloned_messages",
		func() int64 { return m.clonedMessages.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddClonedMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *TeeStage) AddClonedMessages(amount int) {
	m.clonedMessages.Add(int64(amount))
}

// IncrementClonedMessages increments the metric by 1.
func (m *TeeStage) IncrementClonedMessages() {
	m.clonedMessages.Add(1)
}

// DecrementClonedMessages decrements the metric by 1.
func (m *TeeStage) DecrementClonedMessages() {
	m.clonedMessages.Add(-1)
}
