// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// EbpfStage structs contains the metrics for the ebpf_stage group.
type EbpfStage struct {
	receivedRecords atomic.Int64
	parsingErrors   atomic.Int64
	receivedBytes   atomic.Int64
}

// NewEbpfStage returns a new instance of the EbpfStage struct.
func NewEbpfStage() *EbpfStage {
	return &EbpfStage{}
}

// InitMetrics initializes the metrics for the EbpfStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *EbpfStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize received_records counter metric
	err = tel.NewCounterMetric("received_records", func() int64 { return m.receivedRecords.Load() })
	if err != nil {
		return err
	}

	// Initialize parsing_errors counter metric
	err = tel.NewCounterMetric("parsing_errors", func() int64 { return m.parsingErrors.Load() })
	if err != nil {
		return err
	}

	// Initialize received_bytes counter metric
	err = tel.NewCounterMetric("received_bytes", func() int64 { return m.receivedBytes.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddReceivedRecords adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *EbpfStage) AddReceivedRecords(amount uint) {
	m.receivedRecords.Add(int64(amount))
}

// IncrementReceivedRecords increments the counter metric by 1.
//
// This function is thread-safe.
func (m *EbpfStage) IncrementReceivedRecords() {
	m.receivedRecords.Add(1)
}

// AddParsingErrors adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *EbpfStage) AddParsingErrors(amount uint) {
	m.parsingErrors.Add(int64(amount))
}

// IncrementParsingErrors increments the counter metric by 1.
//
// This function is thread-safe.
func (m *EbpfStage) IncrementParsingErrors() {
	m.parsingErrors.Add(1)
}

// AddReceivedBytes adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *EbpfStage) AddReceivedBytes(amount uint) {
	m.receivedBytes.Add(int64(amount))
}

// IncrementReceivedBytes increments the counter metric by 1.
//
// This function is thread-safe.
func (m *EbpfStage) IncrementReceivedBytes() {
	m.receivedBytes.Add(1)
}
