// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// FileStage structs contains the metrics for the file_stage group.
type FileStage struct {
	readers       atomic.Int64
	activeReaders atomic.Int64
	readBytes     atomic.Int64
}

// NewFileStage returns a new instance of the FileStage struct.
func NewFileStage() *FileStage {
	return &FileStage{}
}

// InitMetrics initializes the metrics for the FileStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *FileStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize readers up/down counter metric
	err = tel.NewUpDownCounterMetric("readers", func() int64 { return m.readers.Load() })
	if err != nil {
		return err
	}

	// Initialize active_readers up/down counter metric
	err = tel.NewUpDownCounterMetric("active_readers", func() int64 { return m.activeReaders.Load() })
	if err != nil {
		return err
	}

	// Initialize read_bytes counter metric
	err = tel.NewCounterMetric("read_bytes", func() int64 { return m.readBytes.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddReaders adds the given amount to the up/down counter metric.
// The amount to be added must be an integer.
//
// This function is thread-safe.
func (m *FileStage) AddReaders(amount int) {
	m.readers.Add(int64(amount))
}

// IncrementReaders increments the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) IncrementReaders() {
	m.readers.Add(1)
}

// DecrementReaders decrements the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) DecrementReaders() {
	m.readers.Add(-1)
}

// AddActiveReaders adds the given amount to the up/down counter metric.
// The amount to be added must be an integer.
//
// This function is thread-safe.
func (m *FileStage) AddActiveReaders(amount int) {
	m.activeReaders.Add(int64(amount))
}

// IncrementActiveReaders increments the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) IncrementActiveReaders() {
	m.activeReaders.Add(1)
}

// DecrementActiveReaders decrements the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) DecrementActiveReaders() {
	m.activeReaders.Add(-1)
}

// AddReadBytes adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *FileStage) AddReadBytes(amount uint) {
	m.readBytes.Add(int64(amount))
}

// IncrementReadBytes increments the counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) IncrementReadBytes() {
	m.readBytes.Add(1)
}
