// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
	"sync/atomic"
)

// HttpStage structs contains the metrics for the http_stage group.
type HttpStage struct {
	httpServerRequestDuration             *telemetry.FloatHistogram
	httpServerActiveRequests              atomic.Int64
	httpServerRequestBodySize             *telemetry.IntHistogram
	httpServerResponseBodySize            *telemetry.IntHistogram
	gocciaHttpIngressQueueLen             atomic.Int64
	gocciaHttpIngressQueueWaitDuration    *telemetry.FloatHistogram
	gocciaHttpIngressPendingResponses     atomic.Int64
	gocciaHttpIngressResponseWaitDuration *telemetry.FloatHistogram
}

// NewHttpStage returns a new instance of the HttpStage struct.
func NewHttpStage() *HttpStage {
	return &HttpStage{}
}

// InitMetrics initializes the metrics for the HttpStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *HttpStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize http.server.request.duration metric
	m.httpServerRequestDuration, err = tel.NewFloatHistogramMetric(
		"http.server.request.duration",
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(
			0.0001, 0.00025, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10,
		),
	)
	if err != nil {
		return err
	}

	// Initialize http.server.active_requests metric
	err = tel.NewUpDownCounterMetric(
		"http.server.active_requests",
		func() int64 { return m.httpServerActiveRequests.Load() },
		metric.WithUnit("{request}"),
	)
	if err != nil {
		return err
	}

	// Initialize http.server.request.body.size metric
	m.httpServerRequestBodySize, err = tel.NewIntHistogramMetric(
		"http.server.request.body.size",
		metric.WithUnit("By"),
	)
	if err != nil {
		return err
	}

	// Initialize http.server.response.body.size metric
	m.httpServerResponseBodySize, err = tel.NewIntHistogramMetric(
		"http.server.response.body.size",
		metric.WithUnit("By"),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.queue.len metric
	err = tel.NewGaugeMetric(
		"goccia.http.ingress.queue.len",
		func() int64 { return m.gocciaHttpIngressQueueLen.Load() },
		metric.WithUnit("{message}"),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.queue.wait.duration metric
	m.gocciaHttpIngressQueueWaitDuration, err = tel.NewFloatHistogramMetric(
		"goccia.http.ingress.queue.wait.duration",
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(
			0.0001, 0.00025, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10,
		),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.pending_responses metric
	err = tel.NewUpDownCounterMetric(
		"goccia.http.ingress.pending_responses",
		func() int64 { return m.gocciaHttpIngressPendingResponses.Load() },
		metric.WithUnit("{request}"),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.response.wait.duration metric
	m.gocciaHttpIngressResponseWaitDuration, err = tel.NewFloatHistogramMetric(
		"goccia.http.ingress.response.wait.duration",
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(
			0.0001, 0.00025, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10,
		),
	)
	if err != nil {
		return err
	}

	return nil
}

// RecordHttpServerRequestDuration records the given value into the histogram metric.
//
// HttpServerRequestDuration: Duration of HTTP server requests from handler entry until the response is written.
func (m *HttpStage) RecordHttpServerRequestDuration(
	ctx context.Context,
	value float64,
	requestMethod string,
	urlScheme string,
	statusCode int,
	protocolVersion string,
) {
	m.httpServerRequestDuration.Record(
		ctx,
		value,
		attribute.String("http.request.method", requestMethod),
		attribute.String("url.scheme", urlScheme),
		attribute.Int("http.response.status_code", statusCode),
		attribute.String("network.protocol.version", protocolVersion),
	)
}

// RecordHttpServerRequestDurationWithAttributes records the given value
// ans attributes into the histogram metric.
//
// HttpServerRequestDuration: Duration of HTTP server requests from handler entry until the response is written.
func (m *HttpStage) RecordHttpServerRequestDurationWithAttributes(
	ctx context.Context,
	value float64,
	attributes metric.MeasurementOption,
) {
	m.httpServerRequestDuration.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}

// AddHttpServerActiveRequests adds the given amount to the metric.
// The amount can be either positive or negative.
//
// HttpServerActiveRequests: Number of HTTP server requests currently being handled.
func (m *HttpStage) AddHttpServerActiveRequests(amount int) {
	m.httpServerActiveRequests.Add(int64(amount))
}

// IncrementHttpServerActiveRequests increments the metric by 1.
//
// HttpServerActiveRequests: Number of HTTP server requests currently being handled.
func (m *HttpStage) IncrementHttpServerActiveRequests() {
	m.httpServerActiveRequests.Add(1)
}

// DecrementHttpServerActiveRequests decrements the metric by 1.
//
// HttpServerActiveRequests: Number of HTTP server requests currently being handled.
func (m *HttpStage) DecrementHttpServerActiveRequests() {
	m.httpServerActiveRequests.Add(-1)
}

// RecordHttpServerRequestBodySize records the given value into the histogram metric.
//
// HttpServerRequestBodySize: Size of HTTP request bodies observed by the server, including partially read bodies.
func (m *HttpStage) RecordHttpServerRequestBodySize(
	ctx context.Context,
	value int64,
	requestMethod string,
	urlScheme string,
	statusCode int,
	protocolVersion string,
) {
	m.httpServerRequestBodySize.Record(
		ctx,
		value,
		attribute.String("http.request.method", requestMethod),
		attribute.String("url.scheme", urlScheme),
		attribute.Int("http.response.status_code", statusCode),
		attribute.String("network.protocol.version", protocolVersion),
	)
}

// RecordHttpServerRequestBodySizeWithAttributes records the given value
// ans attributes into the histogram metric.
//
// HttpServerRequestBodySize: Size of HTTP request bodies observed by the server, including partially read bodies.
func (m *HttpStage) RecordHttpServerRequestBodySizeWithAttributes(
	ctx context.Context,
	value int64,
	attributes metric.MeasurementOption,
) {
	m.httpServerRequestBodySize.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}

// RecordHttpServerResponseBodySize records the given value into the histogram metric.
//
// HttpServerResponseBodySize: Size of HTTP response bodies successfully written by the server.
func (m *HttpStage) RecordHttpServerResponseBodySize(
	ctx context.Context,
	value int64,
	requestMethod string,
	urlScheme string,
	statusCode int,
	protocolVersion string,
) {
	m.httpServerResponseBodySize.Record(
		ctx,
		value,
		attribute.String("http.request.method", requestMethod),
		attribute.String("url.scheme", urlScheme),
		attribute.Int("http.response.status_code", statusCode),
		attribute.String("network.protocol.version", protocolVersion),
	)
}

// RecordHttpServerResponseBodySizeWithAttributes records the given value
// ans attributes into the histogram metric.
//
// HttpServerResponseBodySize: Size of HTTP response bodies successfully written by the server.
func (m *HttpStage) RecordHttpServerResponseBodySizeWithAttributes(
	ctx context.Context,
	value int64,
	attributes metric.MeasurementOption,
) {
	m.httpServerResponseBodySize.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}

// AddGocciaHttpIngressQueueLen adds the given amount to the metric.
// The amount can be either positive or negative.
//
// GocciaHttpIngressQueueLen: Number of HTTP request messages currently waiting in the ingress output queue.
func (m *HttpStage) AddGocciaHttpIngressQueueLen(amount int) {
	m.gocciaHttpIngressQueueLen.Add(int64(amount))
}

// IncrementGocciaHttpIngressQueueLen increments the metric by 1.
//
// GocciaHttpIngressQueueLen: Number of HTTP request messages currently waiting in the ingress output queue.
func (m *HttpStage) IncrementGocciaHttpIngressQueueLen() {
	m.gocciaHttpIngressQueueLen.Add(1)
}

// DecrementGocciaHttpIngressQueueLen decrements the metric by 1.
//
// GocciaHttpIngressQueueLen: Number of HTTP request messages currently waiting in the ingress output queue.
func (m *HttpStage) DecrementGocciaHttpIngressQueueLen() {
	m.gocciaHttpIngressQueueLen.Add(-1)
}

// RecordGocciaHttpIngressQueueWaitDuration records the given value into the histogram metric.
//
// GocciaHttpIngressQueueWaitDuration: Time spent waiting to enqueue an HTTP request message for downstream processing.
func (m *HttpStage) RecordGocciaHttpIngressQueueWaitDuration(
	ctx context.Context,
	value float64,
	outcome string,
) {
	m.gocciaHttpIngressQueueWaitDuration.Record(
		ctx,
		value,
		attribute.String("outcome", outcome),
	)
}

// RecordGocciaHttpIngressQueueWaitDurationWithAttributes records the given value
// ans attributes into the histogram metric.
//
// GocciaHttpIngressQueueWaitDuration: Time spent waiting to enqueue an HTTP request message for downstream processing.
func (m *HttpStage) RecordGocciaHttpIngressQueueWaitDurationWithAttributes(
	ctx context.Context,
	value float64,
	attributes metric.MeasurementOption,
) {
	m.gocciaHttpIngressQueueWaitDuration.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}

// AddGocciaHttpIngressPendingResponses adds the given amount to the metric.
// The amount can be either positive or negative.
//
// GocciaHttpIngressPendingResponses: Number of HTTP requests currently awaiting a downstream response.
func (m *HttpStage) AddGocciaHttpIngressPendingResponses(amount int) {
	m.gocciaHttpIngressPendingResponses.Add(int64(amount))
}

// IncrementGocciaHttpIngressPendingResponses increments the metric by 1.
//
// GocciaHttpIngressPendingResponses: Number of HTTP requests currently awaiting a downstream response.
func (m *HttpStage) IncrementGocciaHttpIngressPendingResponses() {
	m.gocciaHttpIngressPendingResponses.Add(1)
}

// DecrementGocciaHttpIngressPendingResponses decrements the metric by 1.
//
// GocciaHttpIngressPendingResponses: Number of HTTP requests currently awaiting a downstream response.
func (m *HttpStage) DecrementGocciaHttpIngressPendingResponses() {
	m.gocciaHttpIngressPendingResponses.Add(-1)
}

// RecordGocciaHttpIngressResponseWaitDuration records the given value into the histogram metric.
//
// GocciaHttpIngressResponseWaitDuration: Time spent waiting for a downstream response after a successful queue handoff.
func (m *HttpStage) RecordGocciaHttpIngressResponseWaitDuration(
	ctx context.Context,
	value float64,
	outcome string,
) {
	m.gocciaHttpIngressResponseWaitDuration.Record(
		ctx,
		value,
		attribute.String("outcome", outcome),
	)
}

// RecordGocciaHttpIngressResponseWaitDurationWithAttributes records the given value
// ans attributes into the histogram metric.
//
// GocciaHttpIngressResponseWaitDuration: Time spent waiting for a downstream response after a successful queue handoff.
func (m *HttpStage) RecordGocciaHttpIngressResponseWaitDurationWithAttributes(
	ctx context.Context,
	value float64,
	attributes metric.MeasurementOption,
) {
	m.gocciaHttpIngressResponseWaitDuration.RecordWithAttributes(
		ctx,
		value,
		attributes,
	)
}
