// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"go.opentelemetry.io/otel/metric"
	"sync/atomic"
)

// HttpStage structs contains the metrics for the http_stage group.
type HttpStage struct {
	httpServerRequestDuration             *telemetry.FloatHistogram
	httpServerActiveRequests              atomic.Int64
	httpServerRequestBodySize             *telemetry.IntHistogram
	httpServerResponseBodySize            *telemetry.IntHistogram
	gocciaHttpIngressQueueLen             atomic.Int64
	gocciaHttpIngressQueueWaitDuration    *telemetry.FloatHistogram
	gocciaHttpIngressPendingResponses     atomic.Int64
	gocciaHttpIngressResponseWaitDuration *telemetry.FloatHistogram
}

// NewHttpStage returns a new instance of the HttpStage struct.
func NewHttpStage() *HttpStage {
	return &HttpStage{}
}

// InitMetrics initializes the metrics for the HttpStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *HttpStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize http.server.request.duration metric
	m.httpServerRequestDuration, err = tel.NewFloatHistogramMetric("http.server.request.duration")
	if err != nil {
		return err
	}

	// Initialize http.server.active_requests metric
	err = tel.NewUpDownCounterMetric(
		"http.server.active_requests",
		func() int64 { return m.httpServerActiveRequests.Load() },
		metric.WithUnit("{request}"),
	)
	if err != nil {
		return err
	}

	// Initialize http.server.request.body.size metric
	m.httpServerRequestBodySize, err = tel.NewIntHistogramMetric("http.server.request.body.size")
	if err != nil {
		return err
	}

	// Initialize http.server.response.body.size metric
	m.httpServerResponseBodySize, err = tel.NewIntHistogramMetric("http.server.response.body.size")
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.queue.len metric
	err = tel.NewGaugeMetric(
		"goccia.http.ingress.queue.len",
		func() int64 { return m.gocciaHttpIngressQueueLen.Load() },
		metric.WithUnit("{message}"),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.queue.wait.duration metric
	m.gocciaHttpIngressQueueWaitDuration, err = tel.NewFloatHistogramMetric("goccia.http.ingress.queue.wait.duration")
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.pending_responses metric
	err = tel.NewUpDownCounterMetric(
		"goccia.http.ingress.pending_responses",
		func() int64 { return m.gocciaHttpIngressPendingResponses.Load() },
		metric.WithUnit("{request}"),
	)
	if err != nil {
		return err
	}

	// Initialize goccia.http.ingress.response.wait.duration metric
	m.gocciaHttpIngressResponseWaitDuration, err = tel.NewFloatHistogramMetric("goccia.http.ingress.response.wait.duration")
	if err != nil {
		return err
	}

	return nil
}

// RecordHttpServerRequestDuration records the given value into the histogram metric.
func (m *HttpStage) RecordHttpServerRequestDuration(ctx context.Context, value float64) {
	m.httpServerRequestDuration.Record(ctx, value)
}

// AddHttpServerActiveRequests adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *HttpStage) AddHttpServerActiveRequests(amount int) {
	m.httpServerActiveRequests.Add(int64(amount))
}

// IncrementHttpServerActiveRequests increments the metric by 1.
func (m *HttpStage) IncrementHttpServerActiveRequests() {
	m.httpServerActiveRequests.Add(1)
}

// DecrementHttpServerActiveRequests decrements the metric by 1.
func (m *HttpStage) DecrementHttpServerActiveRequests() {
	m.httpServerActiveRequests.Add(-1)
}

// RecordHttpServerRequestBodySize records the given value into the histogram metric.
func (m *HttpStage) RecordHttpServerRequestBodySize(ctx context.Context, value int64) {
	m.httpServerRequestBodySize.Record(ctx, value)
}

// RecordHttpServerResponseBodySize records the given value into the histogram metric.
func (m *HttpStage) RecordHttpServerResponseBodySize(ctx context.Context, value int64) {
	m.httpServerResponseBodySize.Record(ctx, value)
}

// AddGocciaHttpIngressQueueLen adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *HttpStage) AddGocciaHttpIngressQueueLen(amount int) {
	m.gocciaHttpIngressQueueLen.Add(int64(amount))
}

// IncrementGocciaHttpIngressQueueLen increments the metric by 1.
func (m *HttpStage) IncrementGocciaHttpIngressQueueLen() {
	m.gocciaHttpIngressQueueLen.Add(1)
}

// DecrementGocciaHttpIngressQueueLen decrements the metric by 1.
func (m *HttpStage) DecrementGocciaHttpIngressQueueLen() {
	m.gocciaHttpIngressQueueLen.Add(-1)
}

// RecordGocciaHttpIngressQueueWaitDuration records the given value into the histogram metric.
func (m *HttpStage) RecordGocciaHttpIngressQueueWaitDuration(ctx context.Context, value float64) {
	m.gocciaHttpIngressQueueWaitDuration.Record(ctx, value)
}

// AddGocciaHttpIngressPendingResponses adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *HttpStage) AddGocciaHttpIngressPendingResponses(amount int) {
	m.gocciaHttpIngressPendingResponses.Add(int64(amount))
}

// IncrementGocciaHttpIngressPendingResponses increments the metric by 1.
func (m *HttpStage) IncrementGocciaHttpIngressPendingResponses() {
	m.gocciaHttpIngressPendingResponses.Add(1)
}

// DecrementGocciaHttpIngressPendingResponses decrements the metric by 1.
func (m *HttpStage) DecrementGocciaHttpIngressPendingResponses() {
	m.gocciaHttpIngressPendingResponses.Add(-1)
}

// RecordGocciaHttpIngressResponseWaitDuration records the given value into the histogram metric.
func (m *HttpStage) RecordGocciaHttpIngressResponseWaitDuration(ctx context.Context, value float64) {
	m.gocciaHttpIngressResponseWaitDuration.Record(ctx, value)
}
