// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// KafkaStage structs contains the metrics for the kafka_stage group.
type KafkaStage struct {
	receivedMessages atomic.Int64
	receivedBytes    atomic.Int64
}

// NewKafkaStage returns a new instance of the KafkaStage struct.
func NewKafkaStage() *KafkaStage {
	return &KafkaStage{}
}

// InitMetrics initializes the metrics for the KafkaStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *KafkaStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize received_messages counter metric
	err = tel.NewCounterMetric("received_messages", func() int64 { return m.receivedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize received_bytes counter metric
	err = tel.NewCounterMetric("received_bytes", func() int64 { return m.receivedBytes.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddReceivedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *KafkaStage) AddReceivedMessages(amount uint) {
	m.receivedMessages.Add(int64(amount))
}

// IncrementReceivedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *KafkaStage) IncrementReceivedMessages() {
	m.receivedMessages.Add(1)
}

// AddReceivedBytes adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *KafkaStage) AddReceivedBytes(amount uint) {
	m.receivedBytes.Add(int64(amount))
}

// IncrementReceivedBytes increments the counter metric by 1.
//
// This function is thread-safe.
func (m *KafkaStage) IncrementReceivedBytes() {
	m.receivedBytes.Add(1)
}
