// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// TcpStage structs contains the metrics for the tcp_stage group.
type TcpStage struct {
	openConnections  atomic.Int64
	receivedMessages atomic.Int64
	receivedBytes    atomic.Int64
}

// NewTcpStage returns a new instance of the TcpStage struct.
func NewTcpStage() *TcpStage {
	return &TcpStage{}
}

// InitMetrics initializes the metrics for the TcpStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *TcpStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize open_connections up/down counter metric
	err = tel.NewUpDownCounterMetric("open_connections", func() int64 { return m.openConnections.Load() })
	if err != nil {
		return err
	}

	// Initialize received_messages counter metric
	err = tel.NewCounterMetric("received_messages", func() int64 { return m.receivedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize received_bytes counter metric
	err = tel.NewCounterMetric("received_bytes", func() int64 { return m.receivedBytes.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddOpenConnections adds the given amount to the up/down counter metric.
// The amount to be added must be an integer.
//
// This function is thread-safe.
func (m *TcpStage) AddOpenConnections(amount int) {
	m.openConnections.Add(int64(amount))
}

// IncrementOpenConnections increments the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *TcpStage) IncrementOpenConnections() {
	m.openConnections.Add(1)
}

// DecrementOpenConnections decrements the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *TcpStage) DecrementOpenConnections() {
	m.openConnections.Add(-1)
}

// AddReceivedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *TcpStage) AddReceivedMessages(amount uint) {
	m.receivedMessages.Add(int64(amount))
}

// IncrementReceivedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *TcpStage) IncrementReceivedMessages() {
	m.receivedMessages.Add(1)
}

// AddReceivedBytes adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *TcpStage) AddReceivedBytes(amount uint) {
	m.receivedBytes.Add(int64(amount))
}

// IncrementReceivedBytes increments the counter metric by 1.
//
// This function is thread-safe.
func (m *TcpStage) IncrementReceivedBytes() {
	m.receivedBytes.Add(1)
}
