// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// TcpStage structs contains the metrics for the tcp_stage group.
type TcpStage struct {
	openConnections  atomic.Int64
	receivedMessages atomic.Int64
	receivedBytes    atomic.Int64
}

// NewTcpStage returns a new instance of the TcpStage struct.
func NewTcpStage() *TcpStage {
	return &TcpStage{}
}

// InitMetrics initializes the metrics for the TcpStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *TcpStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize open_connections metric
	err = tel.NewUpDownCounterMetric(
		"open_connections",
		func() int64 { return m.openConnections.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize received_messages metric
	err = tel.NewCounterMetric(
		"received_messages",
		func() int64 { return m.receivedMessages.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize received_bytes metric
	err = tel.NewCounterMetric(
		"received_bytes",
		func() int64 { return m.receivedBytes.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddOpenConnections adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *TcpStage) AddOpenConnections(amount int) {
	m.openConnections.Add(int64(amount))
}

// IncrementOpenConnections increments the metric by 1.
func (m *TcpStage) IncrementOpenConnections() {
	m.openConnections.Add(1)
}

// DecrementOpenConnections decrements the metric by 1.
func (m *TcpStage) DecrementOpenConnections() {
	m.openConnections.Add(-1)
}

// AddReceivedMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *TcpStage) AddReceivedMessages(amount int) {
	m.receivedMessages.Add(int64(amount))
}

// IncrementReceivedMessages increments the metric by 1.
func (m *TcpStage) IncrementReceivedMessages() {
	m.receivedMessages.Add(1)
}

// DecrementReceivedMessages decrements the metric by 1.
func (m *TcpStage) DecrementReceivedMessages() {
	m.receivedMessages.Add(-1)
}

// AddReceivedBytes adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *TcpStage) AddReceivedBytes(amount int) {
	m.receivedBytes.Add(int64(amount))
}

// IncrementReceivedBytes increments the metric by 1.
func (m *TcpStage) IncrementReceivedBytes() {
	m.receivedBytes.Add(1)
}

// DecrementReceivedBytes decrements the metric by 1.
func (m *TcpStage) DecrementReceivedBytes() {
	m.receivedBytes.Add(-1)
}
