// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// TickerStage structs contains the metrics for the ticker_stage group.
type TickerStage struct {
	triggeredMessages atomic.Int64
}

// NewTickerStage returns a new instance of the TickerStage struct.
func NewTickerStage() *TickerStage {
	return &TickerStage{}
}

// InitMetrics initializes the metrics for the TickerStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *TickerStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize triggered_messages metric
	err = tel.NewCounterMetric(
		"triggered_messages",
		func() int64 { return m.triggeredMessages.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddTriggeredMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *TickerStage) AddTriggeredMessages(amount int) {
	m.triggeredMessages.Add(int64(amount))
}

// IncrementTriggeredMessages increments the metric by 1.
func (m *TickerStage) IncrementTriggeredMessages() {
	m.triggeredMessages.Add(1)
}

// DecrementTriggeredMessages decrements the metric by 1.
func (m *TickerStage) DecrementTriggeredMessages() {
	m.triggeredMessages.Add(-1)
}
