// Code generated by metrics-maker. DO NOT EDIT.

package output

import (
	"sync/atomic"

	"github.com/FerroO2000/goccia/internal/telemetry"
)

type Stage struct {
	countedItems atomic.Int64

	currentItems atomic.Int64
}

func (m *Stage) InitMetrcis(tel *telemetry.Telemetry) {

	tel.NewCounterMetric("counted_items", func() int64 { return m.countedItems.Load() })

	tel.NewUpDownCounterMetric("current_items", func() int64 { return m.currentItems.Load() })

}

func (m *Stage) AddCountedItems(amount int) {
	m.countedItems.Add(int64(amount))
}

func (m *Stage) IncrementCountedItems() {
	m.countedItems.Add(1)
}

func (m *Stage) AddCurrentItems(amount int) {
	m.currentItems.Add(int64(amount))
}

func (m *Stage) IncrementCurrentItems() {
	m.currentItems.Add(1)
}

func (m *Stage) DecrementCurrentItems() {
	m.currentItems.Add(-1)
}
