// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"context"
	"sync/atomic"

	"github.com/FerroO2000/goccia/internal/telemetry"
)

// EgressStage structs contains the metrics for the egress_stage group.
type EgressStage struct {
	deliveredMessages          atomic.Int64
	deliveringErrors           atomic.Int64
	totalMessageProcessingTime *telemetry.IntHistogram
}

// NewEgressStage returns a new instance of the EgressStage struct.
func NewEgressStage() *EgressStage {
	return &EgressStage{}
}

// InitMetrics initializes the metrics for the EgressStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *EgressStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize delivered_messages metric
	err = tel.NewCounterMetric(
		"delivered_messages",
		func() int64 { return m.deliveredMessages.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize delivering_errors metric
	err = tel.NewCounterMetric(
		"delivering_errors",
		func() int64 { return m.deliveringErrors.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize total_message_processing_time metric
	m.totalMessageProcessingTime, err = tel.NewIntHistogramMetric("total_message_processing_time")
	if err != nil {
		return err
	}

	return nil
}

// AddDeliveredMessages adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *EgressStage) AddDeliveredMessages(amount int) {
	m.deliveredMessages.Add(int64(amount))
}

// IncrementDeliveredMessages increments the metric by 1.
func (m *EgressStage) IncrementDeliveredMessages() {
	m.deliveredMessages.Add(1)
}

// DecrementDeliveredMessages decrements the metric by 1.
func (m *EgressStage) DecrementDeliveredMessages() {
	m.deliveredMessages.Add(-1)
}

// AddDeliveringErrors adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *EgressStage) AddDeliveringErrors(amount int) {
	m.deliveringErrors.Add(int64(amount))
}

// IncrementDeliveringErrors increments the metric by 1.
func (m *EgressStage) IncrementDeliveringErrors() {
	m.deliveringErrors.Add(1)
}

// DecrementDeliveringErrors decrements the metric by 1.
func (m *EgressStage) DecrementDeliveringErrors() {
	m.deliveringErrors.Add(-1)
}

// RecordTotalMessageProcessingTime records the given value into the histogram metric.
func (m *EgressStage) RecordTotalMessageProcessingTime(ctx context.Context, value int64) {
	m.totalMessageProcessingTime.Record(ctx, value)
}
