// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"go.opentelemetry.io/otel/metric"
	"sync/atomic"
)

// EgressStage structs contains the metrics for the egress_stage group.
type EgressStage struct {
	deliveredMessages          atomic.Int64
	deliveringErrors           atomic.Int64
	totalMessageProcessingTime *telemetry.Histogram
}

// InitMetrics initializes the metrics for the EgressStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *EgressStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize delivered_messages counter metric
	err = tel.NewCounterMetric("delivered_messages", func() int64 { return m.deliveredMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize delivering_errors counter metric
	err = tel.NewCounterMetric("delivering_errors", func() int64 { return m.deliveringErrors.Load() })
	if err != nil {
		return err
	}

	// Initialize total_message_processing_time histogram metric
	m.totalMessageProcessingTime, err = tel.NewHistogramMetric("total_message_processing_time", metric.WithUnit("ms"))
	if err != nil {
		return err
	}

	return nil
}

// AddDeliveredMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *EgressStage) AddDeliveredMessages(amount uint) {
	m.deliveredMessages.Add(int64(amount))
}

// IncrementDeliveredMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *EgressStage) IncrementDeliveredMessages() {
	m.deliveredMessages.Add(1)
}

// AddDeliveringErrors adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *EgressStage) AddDeliveringErrors(amount uint) {
	m.deliveringErrors.Add(int64(amount))
}

// IncrementDeliveringErrors increments the counter metric by 1.
//
// This function is thread-safe.
func (m *EgressStage) IncrementDeliveringErrors() {
	m.deliveringErrors.Add(1)
}

// RecordTotalMessageProcessingTime records the given value into the histogram metric.
//
// This function is thread-safe.
func (m *EgressStage) RecordTotalMessageProcessingTime(ctx context.Context, value int) {
	m.totalMessageProcessingTime.Record(ctx, int64(value))
}
