// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// ProcessorStage structs contains the metrics for the processor_stage group.
type ProcessorStage struct {
	processedMessages atomic.Int64
	droppedMessages   atomic.Int64
	processingErrors  atomic.Int64
}

// NewProcessorStage returns a new instance of the ProcessorStage struct.
func NewProcessorStage() *ProcessorStage {
	return &ProcessorStage{}
}

// InitMetrics initializes the metrics for the ProcessorStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *ProcessorStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize processed_messages counter metric
	err = tel.NewCounterMetric("processed_messages", func() int64 { return m.processedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize dropped_messages counter metric
	err = tel.NewCounterMetric("dropped_messages", func() int64 { return m.droppedMessages.Load() })
	if err != nil {
		return err
	}

	// Initialize processing_errors counter metric
	err = tel.NewCounterMetric("processing_errors", func() int64 { return m.processingErrors.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddProcessedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *ProcessorStage) AddProcessedMessages(amount uint) {
	m.processedMessages.Add(int64(amount))
}

// IncrementProcessedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) IncrementProcessedMessages() {
	m.processedMessages.Add(1)
}

// AddDroppedMessages adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *ProcessorStage) AddDroppedMessages(amount uint) {
	m.droppedMessages.Add(int64(amount))
}

// IncrementDroppedMessages increments the counter metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) IncrementDroppedMessages() {
	m.droppedMessages.Add(1)
}

// AddProcessingErrors adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *ProcessorStage) AddProcessingErrors(amount uint) {
	m.processingErrors.Add(int64(amount))
}

// IncrementProcessingErrors increments the counter metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) IncrementProcessingErrors() {
	m.processingErrors.Add(1)
}
