// Code generated by metrics-gen. DO NOT EDIT.

package output

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// EgressStage structs contains the metrics for the egress_stage group.
type EgressStage struct {
	countedItems   atomic.Int64
	currentItems   atomic.Int64
	intHistogram   *telemetry.IntHistogram
	floatHistogram *telemetry.FloatHistogram
}

// NewEgressStage returns a new instance of the EgressStage struct.
func NewEgressStage() *EgressStage {
	return &EgressStage{}
}

// InitMetrics initializes the metrics for the EgressStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *EgressStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize counted_items counter metric
	err = tel.NewCounterMetric("counted_items", func() int64 { return m.countedItems.Load() })
	if err != nil {
		return err
	}

	// Initialize current_items up/down counter metric
	err = tel.NewUpDownCounterMetric("current_items", func() int64 { return m.currentItems.Load() })
	if err != nil {
		return err
	}

	// Initialize int_histogram histogram metric
	m.intHistogram, err = tel.NewIntHistogramMetric("int_histogram")
	if err != nil {
		return err
	}

	// Initialize float_histogram histogram metric
	m.floatHistogram, err = tel.NewFloatHistogramMetric("float_histogram")
	if err != nil {
		return err
	}

	return nil
}

// AddCountedItems adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *EgressStage) AddCountedItems(amount uint) {
	m.countedItems.Add(int64(amount))
}

// IncrementCountedItems increments the counter metric by 1.
//
// This function is thread-safe.
func (m *EgressStage) IncrementCountedItems() {
	m.countedItems.Add(1)
}

// AddCurrentItems adds the given amount to the up/down counter metric.
// The amount to be added must be an integer.
//
// This function is thread-safe.
func (m *EgressStage) AddCurrentItems(amount int) {
	m.currentItems.Add(int64(amount))
}

// IncrementCurrentItems increments the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *EgressStage) IncrementCurrentItems() {
	m.currentItems.Add(1)
}

// DecrementCurrentItems decrements the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *EgressStage) DecrementCurrentItems() {
	m.currentItems.Add(-1)
}

// RecordIntHistogram records the given value into the histogram metric.
//
// This function is thread-safe.
func (m *EgressStage) RecordIntHistogram(ctx context.Context, value int64) {
	m.intHistogram.Record(ctx, value)
}

// RecordFloatHistogram records the given value into the histogram metric.
//
// This function is thread-safe.
func (m *EgressStage) RecordFloatHistogram(ctx context.Context, value float64) {
	m.floatHistogram.Record(ctx, value)
}
