// Code generated by metrics-gen. DO NOT EDIT.

package output

import (
	"context"
	"github.com/FerroO2000/goccia/internal/telemetry"
	"go.opentelemetry.io/otel/attribute"
	"sync/atomic"
)

// EgressStage structs contains the metrics for the egress_stage group.
type EgressStage struct {
	countedItems   atomic.Int64
	currentItems   atomic.Int64
	intHistogram   *telemetry.IntHistogram
	floatHistogram *telemetry.FloatHistogram
}

// NewEgressStage returns a new instance of the EgressStage struct.
func NewEgressStage() *EgressStage {
	return &EgressStage{}
}

// InitMetrics initializes the metrics for the EgressStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *EgressStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize counted_items metric
	err = tel.NewCounterMetric(
		"counted_items",
		func() int64 { return m.countedItems.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize current_items metric
	err = tel.NewUpDownCounterMetric(
		"current_items",
		func() int64 { return m.currentItems.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize int_histogram metric
	m.intHistogram, err = tel.NewIntHistogramMetric(
		"int_histogram",
	)
	if err != nil {
		return err
	}

	// Initialize float_histogram metric
	m.floatHistogram, err = tel.NewFloatHistogramMetric(
		"float_histogram",
	)
	if err != nil {
		return err
	}

	return nil
}

// AddCountedItems adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *EgressStage) AddCountedItems(amount int) {
	m.countedItems.Add(int64(amount))
}

// IncrementCountedItems increments the metric by 1.
func (m *EgressStage) IncrementCountedItems() {
	m.countedItems.Add(1)
}

// DecrementCountedItems decrements the metric by 1.
func (m *EgressStage) DecrementCountedItems() {
	m.countedItems.Add(-1)
}

// AddCurrentItems adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *EgressStage) AddCurrentItems(amount int) {
	m.currentItems.Add(int64(amount))
}

// IncrementCurrentItems increments the metric by 1.
func (m *EgressStage) IncrementCurrentItems() {
	m.currentItems.Add(1)
}

// DecrementCurrentItems decrements the metric by 1.
func (m *EgressStage) DecrementCurrentItems() {
	m.currentItems.Add(-1)
}

// RecordIntHistogram records the given value into the histogram metric.
func (m *EgressStage) RecordIntHistogram(
	ctx context.Context,
	value int64,
	arg1 string,
	arg2 bool,
) {
	m.intHistogram.Record(
		ctx,
		value,
		attribute.String("arg1", arg1),
		attribute.Bool("arg2", arg2),
	)
}

// RecordIntHistogramWithAttributes records the given value
// ans attributes into the histogram metric.
func (m *EgressStage) RecordIntHistogramWithAttributes(
	ctx context.Context,
	value int64,
	attributes []attribute.KeyValue,
) {
	m.intHistogram.Record(
		ctx,
		value,
		attributes...,
	)
}

// RecordFloatHistogram records the given value into the histogram metric.
func (m *EgressStage) RecordFloatHistogram(
	ctx context.Context,
	value float64,
	arg1 int,
	arg2 float64,
) {
	m.floatHistogram.Record(
		ctx,
		value,
		attribute.Int("arg1", arg1),
		attribute.Float64("arg2", arg2),
	)
}

// RecordFloatHistogramWithAttributes records the given value
// ans attributes into the histogram metric.
func (m *EgressStage) RecordFloatHistogramWithAttributes(
	ctx context.Context,
	value float64,
	attributes []attribute.KeyValue,
) {
	m.floatHistogram.Record(
		ctx,
		value,
		attributes...,
	)
}
