// Code generated by metrics-gen. DO NOT EDIT.

package output

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// ProcessorStage structs contains the metrics for the processor_stage group.
type ProcessorStage struct {
	countedItems atomic.Int64
	currentItems atomic.Int64
	myGauge      atomic.Int64
}

// NewProcessorStage returns a new instance of the ProcessorStage struct.
func NewProcessorStage() *ProcessorStage {
	return &ProcessorStage{}
}

// InitMetrics initializes the metrics for the ProcessorStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *ProcessorStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize counted_items counter metric
	err = tel.NewCounterMetric("counted_items", func() int64 { return m.countedItems.Load() })
	if err != nil {
		return err
	}

	// Initialize current_items up/down counter metric
	err = tel.NewUpDownCounterMetric("current_items", func() int64 { return m.currentItems.Load() })
	if err != nil {
		return err
	}

	// Initialize my_gauge gauge metric
	err = tel.NewGaugeMetric("my_gauge", func() int64 { return m.myGauge.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddCountedItems adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *ProcessorStage) AddCountedItems(amount uint) {
	m.countedItems.Add(int64(amount))
}

// IncrementCountedItems increments the counter metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) IncrementCountedItems() {
	m.countedItems.Add(1)
}

// AddCurrentItems adds the given amount to the up/down counter metric.
// The amount to be added must be an integer.
//
// This function is thread-safe.
func (m *ProcessorStage) AddCurrentItems(amount int) {
	m.currentItems.Add(int64(amount))
}

// IncrementCurrentItems increments the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) IncrementCurrentItems() {
	m.currentItems.Add(1)
}

// DecrementCurrentItems decrements the up/down counter metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) DecrementCurrentItems() {
	m.currentItems.Add(-1)
}

// AddMyGauge adds the given amount to the gauge metric.
// The amount to be added must be an integer.
//
// This function is thread-safe.
func (m *ProcessorStage) AddMyGauge(amount int) {
	m.myGauge.Add(int64(amount))
}

// IncrementMyGauge increments the gauge metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) IncrementMyGauge() {
	m.myGauge.Add(1)
}

// DecrementMyGauge decrements the gauge metric by 1.
//
// This function is thread-safe.
func (m *ProcessorStage) DecrementMyGauge() {
	m.myGauge.Add(-1)
}
