package ingress

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"unsafe"

	"github.com/FerroO2000/goccia/ingress/metrics"
	"github.com/FerroO2000/goccia/internal/config"
	"github.com/FerroO2000/goccia/internal/message"
	"github.com/FerroO2000/goccia/internal/stage"
	"github.com/FerroO2000/goccia/internal/stage/env"
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// ─── Config ─────────────────────────────────────────────────────────────────|

type ebpfObjs interface {
	Close() error
}

type ebpfObjsPtr[O any] interface {
	*O
	ebpfObjs
}

// EBPFLoadFn loads the embedded CollectionSpec for bpf.
// This function is generated by bpf2go
type EBPFLoadFn func() (*ebpf.CollectionSpec, error)

// EBPFLinkFn is used to link the given eBPF objects
// to a specific hook that implements the [link.Link] interface.
type EBPFLinkFn[O any, OPtr ebpfObjsPtr[O]] func(objs OPtr) (link.Link, error)

// EBPFRingBufferGetter is used to extract the ring buffer
// from the given eBPF objects.
type EBPFRingBufferGetter[O any, OPtr ebpfObjsPtr[O]] func(objs OPtr) *ebpf.Map

// Default values for the ebpf ingress stage configuration.
const (
	DefaultEBPFConfigUseUnsafe = false
)

// EBPFConfig is the configuration for the ebpf ingress stage.
type EBPFConfig[O any, OPtr ebpfObjsPtr[O]] struct {
	// LoadFn defines the function to load the eBPF spec.
	LoadFn EBPFLoadFn

	// LinkFn defines the function to link the eBPF program.
	LinkFn EBPFLinkFn[O, OPtr]

	// RingBufferGetter defines the function to get the ring buffer from the eBPF program.
	RingBufferGetter EBPFRingBufferGetter[O, OPtr]

	// UseUnsafe states whether the data read from the ring buffer should be
	// converted to a Go struct using an unsafe cast. Otherwise, the data is
	// converted with [binary.Read], which is slower.
	UseUnsafe bool

	// CollectionOptions defines the options for loading the eBPF collection.
	CollectionOptions *ebpf.CollectionOptions
}

// NewEBPFConfig returns the default configuration for the ebpf ingress stage.
func NewEBPFConfig[O any, OPtr ebpfObjsPtr[O]](
	loadFn EBPFLoadFn, attachFn EBPFLinkFn[O, OPtr], ringBufferGetter EBPFRingBufferGetter[O, OPtr],
) *EBPFConfig[O, OPtr] {

	return &EBPFConfig[O, OPtr]{
		LoadFn:            loadFn,
		LinkFn:            attachFn,
		RingBufferGetter:  ringBufferGetter,
		UseUnsafe:         DefaultEBPFConfigUseUnsafe,
		CollectionOptions: nil,
	}
}

// Validate checks the configuration.
func (c *EBPFConfig[O, OPtr]) Validate(_ *config.AnomalyCollector) {}

// ─── Message ────────────────────────────────────────────────────────────────|

var _ msgBody = (*EBPFMessage[any])(nil)

// EBPFMessage is the message type for the ebpf ingress stage.
type EBPFMessage[T any] struct {
	// Data is the parsed content of the data coming from the eBPF ring buffer.
	Data T
}

// NewEBPFMessage returns a new ebpf message.
func NewEBPFMessage[T any](data T) *EBPFMessage[T] {
	return &EBPFMessage[T]{
		Data: data,
	}
}

// Destroy cleans up the message.
func (m *EBPFMessage[T]) Destroy() {}

// ─── Environment ────────────────────────────────────────────────────────────|

type ebpfEnv[T any, O any, OPtr ebpfObjsPtr[O]] struct {
	*env.BaseEnv[*EBPFConfig[O, OPtr], *metrics.EbpfStage]

	objs OPtr
	link link.Link

	// rb        *ringbuf.Reader
	eventSize int
}

func newEBPFEnv[T any, O any, OPtr ebpfObjsPtr[O]](config *EBPFConfig[O, OPtr]) *ebpfEnv[T, O, OPtr] {
	return &ebpfEnv[T, O, OPtr]{
		BaseEnv: env.NewIngressEnv(config, metrics.NewEbpfStage()),
	}
}

func (ee *ebpfEnv[T, O, OPtr]) Init(ctx context.Context) error {
	if err := ee.BaseEnv.Init(ctx); err != nil {
		return err
	}

	// Remove resource limits for locked memory
	if err := rlimit.RemoveMemlock(); err != nil {
		ee.Tel.LogError("failed to remove memlock limits", err)
		return err
	}

	// Load the compiled eBPF ELF file
	spec, err := ee.Config.LoadFn()
	if err != nil {
		ee.Tel.LogError("failed to load eBPF spec", err)
		return err
	}

	// Load the eBPF objects
	var dummyObjs O
	objs := OPtr(&dummyObjs)
	if err := spec.LoadAndAssign(objs, ee.Config.CollectionOptions); err != nil {
		ee.Tel.LogError("failed to load eBPF objects", err)
		return err
	}
	ee.objs = objs

	// Get the link
	link, err := ee.Config.LinkFn(objs)
	if err != nil {
		ee.Tel.LogError("failed to attach eBPF program", err)
		return err
	}
	ee.link = link

	// Calculate the event size if useUnsafe is enabled
	if ee.Config.UseUnsafe {
		var event T
		ee.eventSize = int(unsafe.Sizeof(event))
	}

	return nil
}

func (ee *ebpfEnv[T, O, OPtr]) Close(ctx context.Context) {
	// Close the objects
	ee.objs.Close()

	// Close the ebpf link
	ee.link.Close()

	ee.BaseEnv.Close(ctx)
}

// ─── Runner ─────────────────────────────────────────────────────────────────|

type ebpfRunner[T any, O any, OPtr ebpfObjsPtr[O]] struct {
	*runnerBase[*ebpfEnv[T, O, OPtr], *EBPFMessage[T]]

	reader *ringbuf.Reader
}

func newEBPFRunner[T any, O any, OPtr ebpfObjsPtr[O]](outConnector msgConn[*EBPFMessage[T]]) *ebpfRunner[T, O, OPtr] {
	return &ebpfRunner[T, O, OPtr]{
		runnerBase: newRunnerBase[*ebpfEnv[T, O, OPtr]](outConnector),
	}
}

func (er *ebpfRunner[T, O, OPtr]) Init(_ context.Context) error {
	ringBufferMap := er.env.Config.RingBufferGetter(er.env.objs)

	// Open the ring buffer
	rb, err := ringbuf.NewReader(ringBufferMap)
	if err != nil {
		er.env.Tel.LogError("failed to create ring buffer", err)
		return err
	}
	er.reader = rb

	return nil
}

func (er *ebpfRunner[T, O, OPtr]) Run(ctx context.Context) {
	defer er.notifyRunDone()

	done := make(chan struct{})
	defer close(done)

	go func() {
		select {
		case <-ctx.Done():
			er.reader.Close()
		case <-done:
		}
	}()

	for {
		record, err := er.reader.Read()
		if err != nil {
			// Check whether the ring buffer is closed by the context
			if errors.Is(err, ringbuf.ErrClosed) && ctx.Err() != nil {
				return
			}

			er.env.Tel.LogError("failed to read from ring buffer", err)
			return
		}

		outMsg, err := er.handleRecord(ctx, &record)
		if err != nil {
			er.env.Tel.LogError("failed to handle record", err)
			continue
		}

		if err := er.outConnector.Write(outMsg); err != nil {
			outMsg.Destroy()
			er.env.Tel.LogError("failed to write into output connector", err)
		}
	}
}

func (er *ebpfRunner[T, O, OPtr]) handleRecord(ctx context.Context, record *ringbuf.Record) (*msg[*EBPFMessage[T]], error) {
	// Create the trace for the incoming record
	_, span := er.env.Tel.StartTrace(ctx, "receive ebpf record")
	defer span.End()

	data, err := er.parseData(record.RawSample)
	if err != nil {
		er.env.Metrics.IncrementParsingErrors()
		return nil, err
	}

	// Make the message
	ebpfMsg := NewEBPFMessage(data)
	msg := message.NewMessage(ebpfMsg)

	// Save the span into the message
	msg.SaveSpan(span)

	// Update metrics
	er.env.Metrics.IncrementReceivedRecords()

	return msg, nil
}

func (er *ebpfRunner[T, O, OPtr]) parseData(data []byte) (T, error) {
	var res T

	dataLen := len(data)
	er.env.Metrics.AddReceivedBytes(uint(dataLen))

	if er.env.Config.UseUnsafe {
		// Use unsafe struct casting
		if dataLen < er.env.eventSize {
			return res, errors.New("not enough data")
		}

		res = *(*T)(unsafe.Pointer(&data[0]))
		return res, nil
	}

	if err := binary.Read(bytes.NewReader(data), binary.LittleEndian, &res); err != nil {
		return res, err
	}

	return res, nil
}

// ─── Stage ──────────────────────────────────────────────────────────────────|

// EBPFStage is an ingress stage that reads data from an eBPF ring buffer.
type EBPFStage[T any, O any, OPtr ebpfObjsPtr[O]] struct {
	*stage.IngressStage[*EBPFMessage[T], *ebpfEnv[T, O, OPtr]]
}

// NewEBPFStage creates a new ebpf ingress stage.
func NewEBPFStage[T any, O any, OPtr ebpfObjsPtr[O]](
	outConnector msgConn[*EBPFMessage[T]], cfg *EBPFConfig[O, OPtr],
) *EBPFStage[T, O, OPtr] {

	return &EBPFStage[T, O, OPtr]{
		IngressStage: stage.NewIngressStageFromRunner[*EBPFMessage[T]](
			"ebpf", newEBPFEnv[T](cfg), newEBPFRunner[T, O, OPtr](outConnector),
		),
	}
}
