[project]
site_name = "Goccia"
site_description = "Composable streaming pipelines for Go."
site_author = "The Goccia authors"
site_url = "https://ferroo2000.github.io/goccia/"
docs_dir = "pages"
copyright = "Copyright &copy; 2026 The Goccia authors"
repo_url = "https://github.com/FerroO2000/goccia"
repo_name = "FerroO2000/goccia"
extra_css = ["stylesheets/extra.css"]
nav = [
  { "Home" = "index.md" },
  { "Get Started" = "getting-started.md" },
  { "Concepts" = [
    { "Pipeline" = "concepts/pipeline.md" },
    { "Connectors" = "concepts/connectors.md" },
    { "Stages" = "concepts/stages.md" },
  ] },
  { "Built-in Stages" = [
    { "Overview" = "stages/index.md" },
    { "Ingress" = [
      { "Overview" = "stages/ingress/index.md" },
      { "Generic Loop" = "stages/ingress/generic-loop.md" },
      { "Generic Fan-In" = "stages/ingress/generic-fan-in.md" },
      { "Ticker" = "stages/ingress/ticker.md" },
      { "TCP" = "stages/ingress/tcp.md" },
      { "UDP" = "stages/ingress/udp.md" },
      { "File" = "stages/ingress/file.md" },
      { "Kafka" = "stages/ingress/kafka.md" },
      { "eBPF" = "stages/ingress/ebpf.md" },
    ] },
    { "Processor" = [
      { "Overview" = "stages/processor/index.md" },
      { "Generic" = "stages/processor/generic.md" },
      { "Filter" = "stages/processor/filter.md" },
      { "Tee" = "stages/processor/tee.md" },
      { "Merge" = "stages/processor/merge.md" },
      { "CSV" = [
        { "Decoder" = "stages/processor/csv-decoder.md" },
        { "Encoder" = "stages/processor/csv-encoder.md" },
      ] },
      { "CAN" = "stages/processor/can.md" },
      { "Cannelloni" = [
        { "Decoder" = "stages/processor/cannelloni-decoder.md" },
        { "Encoder" = "stages/processor/cannelloni-encoder.md" },
      ] },
      { "ROB" = "stages/processor/rob.md" },
    ] },
    { "Egress" = [
      { "Overview" = "stages/egress/index.md" },
      { "Generic" = "stages/egress/generic.md" },
      { "Sink" = "stages/egress/sink.md" },
      { "TCP" = "stages/egress/tcp.md" },
      { "UDP" = "stages/egress/udp.md" },
      { "File" = "stages/egress/file.md" },
      { "Kafka" = "stages/egress/kafka.md" },
      { "QuestDB" = "stages/egress/questdb.md" },
    ] },
  ] },
  { "Examples" = "examples.md" },
]

[project.theme]
language = "en"
features = [
  "content.code.copy",
  "content.tooltips",
  "navigation.footer",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
logo = "lucide/droplets"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/FerroO2000/goccia"

[project.extra.version]
provider = "mike"
default = ["latest", "development"]
alias = true

[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
