{
 "title": "Goccia",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "traces", "query": "tempo" },
   {
    "name": "service",
    "query": "label_values(go_memory_used_bytes, exported_job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memory_used_bytes{go_memory_type=\"other\",exported_job=\"$service\"}",
     "legendFormat": "{{go_memory_type}}"
    },
    {
     "expr": "go_memory_used_bytes{go_memory_type=\"stack\",exported_job=\"$service\"}",
     "legendFormat": "{{go_memory_type}}"
    }
   ]
  },
  {
   "title": "Message Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(total_message_processing_time_milliseconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(total_message_processing_time_milliseconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(total_message_processing_time_milliseconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(total_message_processing_time_milliseconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(total_message_processing_time_milliseconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "worker_pool_active_workers{exported_job=\"$service\"}",
     "legendFormat": "{{stage_kind}} - {{stage_name}}"
    }
   ]
  },
  {
   "title": "Traces Over 100ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "{resource.service.name=\"$service\" && traceDuration>100ms}",
     "spss": 10
    }
   ]
  },
  {
   "title": "Ingress - eBPF",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(received_bytes_total{stage_kind=\"ingress\",stage_name=\"ebpf\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Received Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "received_bytes_total{stage_kind=\"ingress\",stage_name=\"ebpf\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Received Records",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "received_records_total{stage_kind=\"ingress\",stage_name=\"ebpf\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Parsing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "parsing_errors_total{stage_kind=\"ingress\",stage_name=\"ebpf\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress - File",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readers Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "readers{stage_kind=\"ingress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Active Readers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "active_readers{stage_kind=\"ingress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Read Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(read_bytes_total{stage_kind=\"ingress\",stage_name=\"file\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Read Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "read_bytes_total{stage_kind=\"ingress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress - HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100 * sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\",exported_job=\"$service\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count{exported_job=\"$service\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "targets": [
      {
       "expr": "sum(http_server_active_requests{exported_job=\"$service\"})"
      }
     ]
    },
    {
     "title": "Pending Responses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "res" } },
     "targets": [
      {
       "expr": "sum(goccia_http_ingress_pending_responses{exported_job=\"$service\"})"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (exported_job) (rate(http_server_request_duration_seconds_count{exported_job=\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{exported_job}}"
      }
     ]
    },
    {
     "title": "Request Rate By Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (http_request_method) (rate(http_server_request_duration_seconds_count{exported_job=\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{http_request_method}}"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Request Duration Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum by (le) (rate(http_server_request_duration_seconds_bucket{exported_job=\"$service\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Responses By Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "req" } },
     "targets": [
      {
       "expr": "sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{exported_job=\"$service\"}[$__rate_interval]))",
       "legendFormat": "{{http_response_status_code}}"
      }
     ]
    },
    {
     "title": "Request Body Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_request_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_request_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(http_server_request_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(http_server_request_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Response Body Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_response_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_response_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (rate(http_server_response_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (rate(http_server_response_body_size_bytes_bucket{exported_job=\"$service\"}[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress - Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(received_bytes_total{stage_kind=\"ingress\",stage_name=\"kafka\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Received Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "received_bytes_total{stage_kind=\"ingress\",stage_name=\"kafka\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Received Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "received_messages_total{stage_kind=\"ingress\",stage_name=\"kafka\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress - TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "open_connections{stage_kind=\"ingress\",stage_name=\"tcp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Received Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(received_bytes_total{stage_kind=\"ingress\",stage_name=\"tcp\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Received Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "received_bytes_total{stage_kind=\"ingress\",stage_name=\"tcp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Received Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "received_messages_total{stage_kind=\"ingress\",stage_name=\"tcp\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress - UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(received_bytes_total{stage_kind=\"ingress\",stage_name=\"udp\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Received Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "received_bytes_total{stage_kind=\"ingress\",stage_name=\"udp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Received Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "received_messages_total{stage_kind=\"ingress\",stage_name=\"udp\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - CAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processed_messages_total{stage_kind=\"processor\",stage_name=\"can\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processing_errors_total{stage_kind=\"processor\",stage_name=\"can\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dropped_messages_total{stage_kind=\"processor\",stage_name=\"can\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "CAN Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "can_messages_total{stage_kind=\"processor\",stage_name=\"can\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "CAN Signals",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "can_signals_total{stage_kind=\"processor\",stage_name=\"can\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - Cannelloni Decoder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processed_messages_total{stage_kind=\"processor\",stage_name=\"cannelloni_decoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processing_errors_total{stage_kind=\"processor\",stage_name=\"cannelloni_decoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dropped_messages_total{stage_kind=\"processor\",stage_name=\"cannelloni_decoder\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - Cannelloni Encoder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processed_messages_total{stage_kind=\"processor\",stage_name=\"cannelloni_encoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processing_errors_total{stage_kind=\"processor\",stage_name=\"cannelloni_encoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dropped_messages_total{stage_kind=\"processor\",stage_name=\"cannelloni_encoder\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - CSV Decoder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processed_messages_total{stage_kind=\"processor\",stage_name=\"csv_decoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processing_errors_total{stage_kind=\"processor\",stage_name=\"csv_decoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dropped_messages_total{stage_kind=\"processor\",stage_name=\"csv_decoder\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - CSV Encoder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processed_messages_total{stage_kind=\"processor\",stage_name=\"csv_encoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processing_errors_total{stage_kind=\"processor\",stage_name=\"csv_encoder\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dropped_messages_total{stage_kind=\"processor\",stage_name=\"csv_encoder\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - Custom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processed_messages_total{stage_kind=\"processor\",stage_name=\"custom\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Processing Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processing_errors_total{stage_kind=\"processor\",stage_name=\"custom\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Dropped Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "dropped_messages_total{stage_kind=\"processor\",stage_name=\"custom\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filtered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "filtered_messages_total{stage_kind=\"processor\",stage_name=\"filter\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - ReOrder Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ordered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ordered_messages_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Primary Enqueued Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "primary_enqueued_messages_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Auxiliary Enqueued Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "auxiliary_enqueued_messages_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Out of Order Sequence Number Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "out_of_order_sequence_number_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Duplicated Sequence Number Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "duplicated_sequence_number_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Invalid Sequence Number Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "invalid_sequence_number_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Resets",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "resets_total{stage_kind=\"processor\",stage_name=\"rob\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processor - Tee",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloned Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cloned_messages_total{stage_kind=\"processor\",stage_name=\"tee\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Egress - File",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivered_messages_total{stage_kind=\"egress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivering Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivering_errors_total{stage_kind=\"egress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Written Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(written_bytes_total{stage_kind=\"egress\",stage_name=\"file\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Written Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "written_bytes_total{stage_kind=\"egress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Write Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "write_errors_total{stage_kind=\"egress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Flush Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "flush_errors_total{stage_kind=\"egress\",stage_name=\"file\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Egress - Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivered_messages_total{stage_kind=\"egress\",stage_name=\"kafka\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivering Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivering_errors_total{stage_kind=\"egress\",stage_name=\"kafka\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Egress - Quest DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivered_messages_total{stage_kind=\"egress\",stage_name=\"questdb\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivering Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivering_errors_total{stage_kind=\"egress\",stage_name=\"questdb\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Inserted Rows",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "inserted_rows_total{stage_kind=\"egress\",stage_name=\"questdb\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Egress - TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivered_messages_total{stage_kind=\"egress\",stage_name=\"tcp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivering Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivering_errors_total{stage_kind=\"egress\",stage_name=\"tcp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivered Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(delivered_bytes_total{stage_kind=\"egress\",stage_name=\"tcp\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Delivered Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "delivered_bytes_total{stage_kind=\"egress\",stage_name=\"tcp\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Egress - UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delivered Messages",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivered_messages_total{stage_kind=\"egress\",stage_name=\"udp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivering Errors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "delivering_errors_total{stage_kind=\"egress\",stage_name=\"udp\",exported_job=\"$service\"}"
      }
     ]
    },
    {
     "title": "Delivered Bytes Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(delivered_bytes_total{stage_kind=\"egress\",stage_name=\"udp\",exported_job=\"$service\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Delivered Bytes Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "delivered_bytes_total{stage_kind=\"egress\",stage_name=\"udp\",exported_job=\"$service\"}"
      }
     ]
    }
   ]
  }
 ]
}