// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// FileStage structs contains the metrics for the file_stage group.
type FileStage struct {
	writtenBytes atomic.Int64
	writeErrors  atomic.Int64
	flushErrors  atomic.Int64
}

// NewFileStage returns a new instance of the FileStage struct.
func NewFileStage() *FileStage {
	return &FileStage{}
}

// InitMetrics initializes the metrics for the FileStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *FileStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize written_bytes counter metric
	err = tel.NewCounterMetric("written_bytes", func() int64 { return m.writtenBytes.Load() })
	if err != nil {
		return err
	}

	// Initialize write_errors counter metric
	err = tel.NewCounterMetric("write_errors", func() int64 { return m.writeErrors.Load() })
	if err != nil {
		return err
	}

	// Initialize flush_errors counter metric
	err = tel.NewCounterMetric("flush_errors", func() int64 { return m.flushErrors.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddWrittenBytes adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *FileStage) AddWrittenBytes(amount uint) {
	m.writtenBytes.Add(int64(amount))
}

// IncrementWrittenBytes increments the counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) IncrementWrittenBytes() {
	m.writtenBytes.Add(1)
}

// AddWriteErrors adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *FileStage) AddWriteErrors(amount uint) {
	m.writeErrors.Add(int64(amount))
}

// IncrementWriteErrors increments the counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) IncrementWriteErrors() {
	m.writeErrors.Add(1)
}

// AddFlushErrors adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *FileStage) AddFlushErrors(amount uint) {
	m.flushErrors.Add(int64(amount))
}

// IncrementFlushErrors increments the counter metric by 1.
//
// This function is thread-safe.
func (m *FileStage) IncrementFlushErrors() {
	m.flushErrors.Add(1)
}
