// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// FileStage structs contains the metrics for the file_stage group.
type FileStage struct {
	writtenBytes atomic.Int64
	writeErrors  atomic.Int64
	flushErrors  atomic.Int64
}

// NewFileStage returns a new instance of the FileStage struct.
func NewFileStage() *FileStage {
	return &FileStage{}
}

// InitMetrics initializes the metrics for the FileStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *FileStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize written_bytes metric
	err = tel.NewCounterMetric(
		"written_bytes",
		func() int64 { return m.writtenBytes.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize write_errors metric
	err = tel.NewCounterMetric(
		"write_errors",
		func() int64 { return m.writeErrors.Load() },
	)
	if err != nil {
		return err
	}

	// Initialize flush_errors metric
	err = tel.NewCounterMetric(
		"flush_errors",
		func() int64 { return m.flushErrors.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddWrittenBytes adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *FileStage) AddWrittenBytes(amount int) {
	m.writtenBytes.Add(int64(amount))
}

// IncrementWrittenBytes increments the metric by 1.
func (m *FileStage) IncrementWrittenBytes() {
	m.writtenBytes.Add(1)
}

// DecrementWrittenBytes decrements the metric by 1.
func (m *FileStage) DecrementWrittenBytes() {
	m.writtenBytes.Add(-1)
}

// AddWriteErrors adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *FileStage) AddWriteErrors(amount int) {
	m.writeErrors.Add(int64(amount))
}

// IncrementWriteErrors increments the metric by 1.
func (m *FileStage) IncrementWriteErrors() {
	m.writeErrors.Add(1)
}

// DecrementWriteErrors decrements the metric by 1.
func (m *FileStage) DecrementWriteErrors() {
	m.writeErrors.Add(-1)
}

// AddFlushErrors adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *FileStage) AddFlushErrors(amount int) {
	m.flushErrors.Add(int64(amount))
}

// IncrementFlushErrors increments the metric by 1.
func (m *FileStage) IncrementFlushErrors() {
	m.flushErrors.Add(1)
}

// DecrementFlushErrors decrements the metric by 1.
func (m *FileStage) DecrementFlushErrors() {
	m.flushErrors.Add(-1)
}
