// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// QuestDbStage structs contains the metrics for the quest_db_stage group.
type QuestDbStage struct {
	insertedRows atomic.Int64
}

// NewQuestDbStage returns a new instance of the QuestDbStage struct.
func NewQuestDbStage() *QuestDbStage {
	return &QuestDbStage{}
}

// InitMetrics initializes the metrics for the QuestDbStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *QuestDbStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize inserted_rows counter metric
	err = tel.NewCounterMetric("inserted_rows", func() int64 { return m.insertedRows.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddInsertedRows adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *QuestDbStage) AddInsertedRows(amount uint) {
	m.insertedRows.Add(int64(amount))
}

// IncrementInsertedRows increments the counter metric by 1.
//
// This function is thread-safe.
func (m *QuestDbStage) IncrementInsertedRows() {
	m.insertedRows.Add(1)
}
