// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// TcpStage structs contains the metrics for the tcp_stage group.
type TcpStage struct {
	deliveredBytes atomic.Int64
}

// NewTcpStage returns a new instance of the TcpStage struct.
func NewTcpStage() *TcpStage {
	return &TcpStage{}
}

// InitMetrics initializes the metrics for the TcpStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *TcpStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize delivered_bytes metric
	err = tel.NewCounterMetric(
		"delivered_bytes",
		func() int64 { return m.deliveredBytes.Load() },
	)
	if err != nil {
		return err
	}

	return nil
}

// AddDeliveredBytes adds the given amount to the metric.
// The amount can be either positive or negative.
func (m *TcpStage) AddDeliveredBytes(amount int) {
	m.deliveredBytes.Add(int64(amount))
}

// IncrementDeliveredBytes increments the metric by 1.
func (m *TcpStage) IncrementDeliveredBytes() {
	m.deliveredBytes.Add(1)
}

// DecrementDeliveredBytes decrements the metric by 1.
func (m *TcpStage) DecrementDeliveredBytes() {
	m.deliveredBytes.Add(-1)
}
