// Code generated by metrics-gen. DO NOT EDIT.

package metrics

import (
	"github.com/FerroO2000/goccia/internal/telemetry"
	"sync/atomic"
)

// UdpStage structs contains the metrics for the udp_stage group.
type UdpStage struct {
	deliveredBytes atomic.Int64
}

// NewUdpStage returns a new instance of the UdpStage struct.
func NewUdpStage() *UdpStage {
	return &UdpStage{}
}

// InitMetrics initializes the metrics for the UdpStage.
// It uses the given telemetry instance to create the metrics.
//
// It must be called before using the metrics.
func (m *UdpStage) InitMetrics(tel *telemetry.Telemetry) error {
	var err error

	// Initialize delivered_bytes counter metric
	err = tel.NewCounterMetric("delivered_bytes", func() int64 { return m.deliveredBytes.Load() })
	if err != nil {
		return err
	}

	return nil
}

// AddDeliveredBytes adds the given amount to the counter metric.
// The amount to be added must be a positive integer.
//
// This function is thread-safe.
func (m *UdpStage) AddDeliveredBytes(amount uint) {
	m.deliveredBytes.Add(int64(amount))
}

// IncrementDeliveredBytes increments the counter metric by 1.
//
// This function is thread-safe.
func (m *UdpStage) IncrementDeliveredBytes() {
	m.deliveredBytes.Add(1)
}
